imports:
    - { resource: "resources.yaml" }
    - { resource: "grid.yaml" }
    - { resource: "twig_hooks.yaml" }

#sylius_ui:
#    events:
#        sylius.admin.taxon.update.form:
#            blocks:
#                akeneo: '@SynoliaSyliusAkeneoPlugin/Admin/Event/taxon_attributes_edit_block.html.twig'
